---
collections:
  - name: cisco.ios
    version: 9.1.1
  - name: ansible.netcommon
    version: 7.1.0
  - name: ansible.utils
    version: 5.1.2
  - name: community.general
    version: 9.2.0
  - name: community.network
    version: 5.1.0
  - name: h3c_open.comware
    version: 1.0.2