---
- name: Check H3C IP Addresses
  hosts: h3c_devices
  gather_facts: false
  connection: ansible.netcommon.network_cli
  become: yes
  become_method: ansible.netcommon.enable

  tasks:
    - name: Run command to get IP interface details
      ansible.netcommon.cli_command:
        command: "display ip interface brief"
      register: interface_output

    - name: Filter for lines containing an IP address
      ansible.builtin.set_fact:
        ip_address_lines: "{{ interface_output.stdout_lines | select('regex', '\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}') | list }}"

    - name: Display only the lines with IP addresses
      ansible.builtin.debug:
        msg: "{{ ip_address_lines }}"