---
# Update the command mapping to match actual ansible_network_os values
running_config_command:
  ios: "show running-config"
  nxos: "show running-config"
  eos: "show running-config"
  comware: "display current-configuration"
  ce: "display current-configuration"

save_config_command:
  ios: "write memory"
  nxos: "copy running-config startup-config"
  eos: "write memory"
  comware: "save"
  ce: "save"

# Updated mapping to match actual network OS values from your test
baseline_mapping:
  ios: "Baseline_Cisco"
  nxos: "Baseline_Cisco"
  eos: "Baseline_Cisco"
  comware: "Baseline_H3C"                    # For h3c_open.comware.comware
  ce: "Baseline_Huawei"                      # For community.network.ce

# Configuration sections to check for each OS
config_sections:
  ios:
    - "service password-encryption"
    - "banner login"
    - "line con 0"
    - "line vty"
    - "snmp-server community"
    - "tacacs-server host"
  comware:
    - "header login"
    - "line aux"
    - "line vty"
    - "hwtacacs scheme"
    - "snmp-agent community"
  ce:
    - "user-interface console"
    - "user-interface vty"
    - "hwtacacs-server"
    - "snmp-agent community"