---

- name: Create tempory folder for git
  file: 
    path: "{{ playbook_dir }}/git_folder_temp"
    state: directory
  run_once: true
  delegate_to: localhost

- name: Clone from server
  command: "git clone https://{{ git_username }}:{{ git_token }}@{{ git_server }}/{{ git_username}}/{{ git_repo_name }}.git"
  args:
    chdir: "{{ playbook_dir }}/git_folder_temp"
  delegate_to: localhost
  register: git_clone_result
  run_once: true
  changed_when: git_clone_result.rc == 0

- name: Checkout branch
  command: "git checkout -b {{ git_branch }}"
  args:
    chdir: "{{ playbook_dir }}/git_folder_temp/{{ git_repo_name }}"
  delegate_to: localhost
  run_once: true

- name: pull from branch
  command: "git pull origin {{ git_branch }}"
  args:
    chdir: "{{ playbook_dir }}/git_folder_temp/{{ git_repo_name }}"
  delegate_to: localhost
  run_once: true

- name: Set user name
  command: "git config user.name {{ git_username }}"
  args:
    chdir: "{{ playbook_dir }}/git_folder_temp/{{ git_repo_name }}"
  delegate_to: localhost
  run_once: true

- name: Set user email
  command: "git config user.email {{ git_email }}"
  args:
    chdir: "{{ playbook_dir }}/git_folder_temp/{{ git_repo_name }}"
  delegate_to: localhost
  run_once: true

- name: Create backup directory for device
  file:
    path: "{{ playbook_dir }}/git_folder_temp/{{ git_repo_name }}/3.2-backup/{{ inventory_hostname }}"
    state: directory
  run_once: true
  delegate_to: localhost

- name: Backup running configuration
  copy:
    content: "{{ running_config.stdout }}"
    dest: "{{ playbook_dir }}/git_folder_temp/{{ git_repo_name }}/3.2-backup/{{ inventory_hostname }}/{{ inventory_hostname }}_backup_{{ timestamp }}.txt"
  run_once: true
  delegate_to: localhost

- name: add files
  command: "git add . "
  args:
    chdir: "{{ playbook_dir }}/git_folder_temp/{{ git_repo_name }}"
  delegate_to: localhost
  run_once: true

- name: commit
  command: git commit -m "'{{ git_msg }}'"
  args:
    chdir: "{{ playbook_dir }}/git_folder_temp/{{ git_repo_name }}"
  delegate_to: localhost
  run_once: true

- name: push
  command: "git push --set-upstream origin {{ git_branch }}"
  args:
    chdir: "{{ playbook_dir }}/git_folder_temp/{{ git_repo_name }}"
  delegate_to: localhost
  run_once: true  

- name: Clean up
  file:
    path: "{{ playbook_dir }}/git_folder_temp"
    state: absent
  delegate_to: localhost
  run_once: true
  no_log: true
