---
# roles/config_drift/tasks/main.yml
- name: Get current date and time
  setup:
    filter: ansible_date_time
  delegate_to: localhost
  run_once: true

- name: Initialize drift detection variables
  set_fact:
    drift_results: []
    remediated_devices: []
    failed_devices: []
    baseline_configs: {}
    timestamp: "{{ ansible_date_time.iso8601 | regex_replace(':', '-') }}"
    backup_date: "{{ ansible_date_time.date }}"

- name: Create local backup directory
  file:
    path: "{{ backup_path }}/{{ backup_date }}"
    state: directory
    mode: '0755'
  delegate_to: localhost
  run_once: true
  when: perform_backup | bool

- name: Retrieve baseline configurations
  include_tasks: retrieve_baseline.yml
  run_once: true

- name: Process each device for drift detection
  include_tasks: drift_detection.yml

#- name: Commit and push backups to Git
#  include_tasks: commit_backups.yml
#  run_once: true
#  when: perform_backup | bool
#
#- name: Generate drift summary
#  include_tasks: generate_summary.yml
#  run_once: true