---
- name: Debug baseline_config_dir value
  debug:
    msg: "baseline_config_dir is set to: {{ baseline_config_dir | default('UNDEFINED - PLEASE DEFINE IN VARS') }}"
  delegate_to: localhost

- name: Debug baseline_config_dir contents
  shell: ls -R {{ baseline_config_dir }} || echo "Directory not found or empty"
  register: dir_contents
  delegate_to: localhost
  ignore_errors: true

- name: Display directory contents
  debug:
    var: dir_contents.stdout

- name: Check if baseline files exist and are non-empty
  stat:
    path: "{{ baseline_config_dir }}/{{ item }}/baseline_config.txt"
  loop:
    - cisco
    - h3c
    - huawei
  register: file_stats
  delegate_to: localhost

- name: Display file status
  debug:
    msg: "Vendor {{ item.item }} baseline file exists: {{ item.stat.exists }}, size: {{ item.stat.size | default(0) }} bytes"
  loop: "{{ file_stats.results }}"

- name: Create baseline directory structure if not exists
  file:
    path: "{{ baseline_config_dir }}/{{ item }}"
    state: directory
  loop:
    - cisco
    - h3c
    - huawei
  delegate_to: localhost

- name: Find all baseline configuration files
  find:
    paths: "{{ baseline_config_dir }}"
    patterns: "baseline_config.txt"
    recurse: yes
  register: all_baseline_files
  delegate_to: localhost

- name: Find remediation command files
  find:
    paths: "{{ baseline_config_dir }}"
    patterns: "remediation_commands.txt"
    recurse: yes
  register: remediation_files
  delegate_to: localhost

- name: Load remediation commands
  set_fact:
    remediation_commands: "{{ remediation_commands | default({}) | combine({vendor: remediation_content.split('\n') | reject('match', '^#.*') | reject('equalto', '') | list}) }}"
  vars:
    vendor: "{{ item.path | dirname | basename }}"
    remediation_content: "{{ lookup('file', item.path) }}"
  loop: "{{ remediation_files.files }}"
  delegate_to: localhost
  when: remediation_files.files | length > 0

- name: Debug loaded remediation commands
  debug:
    msg: |
      ========================================
      📚 REMEDIATION COMMANDS LOADED
      ========================================
      Available remediation commands: {{ remediation_commands.keys() | default([]) | list }}
      ========================================
  delegate_to: localhost